# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import item_records_pb2 as item__records__pb2


class ItemsRecordsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PingItemsRecords = channel.unary_unary(
                '/ItemsRecords/PingItemsRecords',
                request_serializer=item__records__pb2.EmptyRequest.SerializeToString,
                response_deserializer=item__records__pb2.PingItemsRecordsResponse.FromString,
                )
        self.GetItemsRecords = channel.unary_unary(
                '/ItemsRecords/GetItemsRecords',
                request_serializer=item__records__pb2.EmptyRequest.SerializeToString,
                response_deserializer=item__records__pb2.GetItemsResponse.FromString,
                )


class ItemsRecordsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PingItemsRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemsRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemsRecordsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PingItemsRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.PingItemsRecords,
                    request_deserializer=item__records__pb2.EmptyRequest.FromString,
                    response_serializer=item__records__pb2.PingItemsRecordsResponse.SerializeToString,
            ),
            'GetItemsRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemsRecords,
                    request_deserializer=item__records__pb2.EmptyRequest.FromString,
                    response_serializer=item__records__pb2.GetItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ItemsRecords', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemsRecords(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PingItemsRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemsRecords/PingItemsRecords',
            item__records__pb2.EmptyRequest.SerializeToString,
            item__records__pb2.PingItemsRecordsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemsRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ItemsRecords/GetItemsRecords',
            item__records__pb2.EmptyRequest.SerializeToString,
            item__records__pb2.GetItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
